baseURL = "https://blog.travisbumgarner.com"
languageCode = "en-us"
title = "Travis Bumgarner"
theme="foobar"
disqusShortname="travisbumgarner"
googleAnalytics="UA-131349056-1"
paginate=5
ignoreErrors = ["error-missing-instagram-accesstoken"]
[taxonomies]
   tools = "tools"
   project = "project"
   topics = "topics"
[params]
   SiteDescription= "I've been an Engineer, Photographer, Entrepreneur, Maker, Writer, Speaker, Teacher, Open Source Contributor, and jack of all trades. Currently, I live in Boston, MA and work as a Software Engineer. These are my ramblings."
   author="Travis Bumgarner"